version: '3'
services:
  jenkins:
    user: root
    image: "redzicleon-jenkins"
    ports:
       - "8080:8080"
       - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - ${WHICH_DOCKER}:/usr/bin/docker

